#pragma once

#include <KNSoft/ZPigeon/Protocol.h>

EXTERN_C_START

#define ZP_USER_MODULE_ID 9
#define ZP_SOFTWARE_MODULE_ID 20
#define ZP_HARDWARE_MODULE_ID 21
#define ZP_UPDATE_MODULE_ID 22
#define ZP_TASK_MODULE_ID 23
#define ZP_FIREWALL_MODULE_ID 24
#define ZP_POWER_MODULE_ID 25
#define ZP_SYSTEM_ADMINISTRATION_MODULE_ID 26
#define ZP_WLAN_MODULE_ID 27
#define ZP_CERTIFICATE_MODULE_ID 28
#define ZP_CLIPBOARD_MODULE_ID 29
#define ZP_CREDENTIAL_MODULE_ID 30
#define ZP_FIRMWARE_MODULE_ID 31
#define ZP_NETWORK_SHARE_MODULE_ID 32
#define ZP_NETWORK_STATUS_MODULE_ID 33
#define ZP_PAGE_FILE_MODULE_ID 34
#define ZP_BLUETOOTH_MODULE_ID 35
#define ZP_KEYBOARD_MODULE_ID 36
#define ZP_LOCATION_MODULE_ID 37
#define ZP_FONT_MODULE_ID 38
#define ZP_APP_CONTAINER_MODULE_ID 39
#define ZP_WINOBJ_MODULE_ID 40
#define ZP_WSL_MODULE_ID 41
#define ZP_UI_AUTOMATION_MODULE_ID 42
#define ZP_PROXY_VPN_MODULE_ID 43
#define ZP_CLIENT_STATUS_MODULE_ID 44
#define ZP_SHADOW_COPY_MODULE_ID 45
#define ZP_BITLOCKER_MODULE_ID 46

#define ZP_MANAGEMENT_MODULE_MASK \
    (ZP_MODULE_BIT(ZP_USER_MODULE_ID) | ZP_MODULE_BIT(ZP_SOFTWARE_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_HARDWARE_MODULE_ID) | ZP_MODULE_BIT(ZP_UPDATE_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_TASK_MODULE_ID) | ZP_MODULE_BIT(ZP_FIREWALL_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_POWER_MODULE_ID) | ZP_MODULE_BIT(ZP_SYSTEM_ADMINISTRATION_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_WLAN_MODULE_ID) | ZP_MODULE_BIT(ZP_CERTIFICATE_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_CLIPBOARD_MODULE_ID) | ZP_MODULE_BIT(ZP_CREDENTIAL_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_FIRMWARE_MODULE_ID) | ZP_MODULE_BIT(ZP_NETWORK_SHARE_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_NETWORK_STATUS_MODULE_ID) | ZP_MODULE_BIT(ZP_PAGE_FILE_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_BLUETOOTH_MODULE_ID) | ZP_MODULE_BIT(ZP_KEYBOARD_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_LOCATION_MODULE_ID) | ZP_MODULE_BIT(ZP_FONT_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_APP_CONTAINER_MODULE_ID) | ZP_MODULE_BIT(ZP_WINOBJ_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_WSL_MODULE_ID) | ZP_MODULE_BIT(ZP_UI_AUTOMATION_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_PROXY_VPN_MODULE_ID) | ZP_MODULE_BIT(ZP_CLIENT_STATUS_MODULE_ID) | \
     ZP_MODULE_BIT(ZP_SHADOW_COPY_MODULE_ID) | ZP_MODULE_BIT(ZP_BITLOCKER_MODULE_ID))

#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_USERS 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_USER 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_SESSIONS 3
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_LOGON_SESSIONS 4
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_USER_PROFILES 5
#define ZP_ADMINISTRATION_OPERATION_CONTROL_USER_PROFILE 6

#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_SOFTWARE 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_SOFTWARE 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_FEATURES 3
#define ZP_ADMINISTRATION_OPERATION_CONTROL_FEATURE 4
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_PACKAGE_PROVIDERS 5
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_SOFTWARE_DEPLOYMENTS 6
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_INPUT_METHODS 7
#define ZP_ADMINISTRATION_OPERATION_CONTROL_INPUT_METHOD 8
#define ZP_ADMINISTRATION_OPERATION_QUERY_PACKAGES 9

#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_HARDWARE 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_HARDWARE 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_UPDATES 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_UPDATE 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_TASKS 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_TASK 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_FIREWALL 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_FIREWALL 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_POWER 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_POWER 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_SYSTEM 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_SYSTEM 2

#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_WLAN 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_WLAN 2
#define ZP_ADMINISTRATION_OPERATION_QUERY_WLAN_PROFILE 3
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_CERTIFICATES 1
#define ZP_ADMINISTRATION_OPERATION_QUERY_CERTIFICATE 2
#define ZP_ADMINISTRATION_OPERATION_QUERY_CERTIFICATE_DATA 3
#define ZP_ADMINISTRATION_OPERATION_CONTROL_CERTIFICATE_DATA 4
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_CERTIFICATE_STORES 5
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_CLIPBOARD 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_CLIPBOARD 2
#define ZP_ADMINISTRATION_OPERATION_WAIT_CLIPBOARD 3
#define ZP_ADMINISTRATION_OPERATION_QUERY_CLIPBOARD_IMAGE 4
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_CREDENTIALS 1
#define ZP_ADMINISTRATION_OPERATION_QUERY_CREDENTIAL 2
#define ZP_ADMINISTRATION_OPERATION_CONTROL_CREDENTIAL 3
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_FIRMWARE_VARIABLES 1
#define ZP_ADMINISTRATION_OPERATION_QUERY_FIRMWARE 2
#define ZP_ADMINISTRATION_OPERATION_QUERY_FIRMWARE_DATA 3
#define ZP_ADMINISTRATION_OPERATION_CONTROL_FIRMWARE_DATA 4

#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_PUBLISHED_SHARES 1
#define ZP_ADMINISTRATION_OPERATION_QUERY_PUBLISHED_SHARE 2
#define ZP_ADMINISTRATION_OPERATION_CONTROL_PUBLISHED_SHARE 3
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_NETWORK_CONNECTIONS 4
#define ZP_ADMINISTRATION_OPERATION_CONTROL_NETWORK_CONNECTION 5
#define ZP_ADMINISTRATION_OPERATION_CONTROL_PUBLISHED_SHARE_SECURITY 6
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_NETWORK_ADAPTERS 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_NETWORK_ADAPTER 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_NETWORK_ROUTES 3
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_NETWORK_ENDPOINTS 4
#define ZP_ADMINISTRATION_OPERATION_CONTROL_NETWORK_ROUTE 5
#define ZP_ADMINISTRATION_OPERATION_CONTROL_NETWORK_ENDPOINT 6

#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_PAGE_FILES 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_PAGE_FILE 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_BLUETOOTH 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_BLUETOOTH 2
#define ZP_ADMINISTRATION_OPERATION_WAIT_KEYBOARD 1
#define ZP_ADMINISTRATION_OPERATION_QUERY_LOCATION 1
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_FONTS 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_FONT 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_APP_CONTAINERS 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_APP_CONTAINER 2
#define ZP_ADMINISTRATION_OPERATION_QUERY_OBJECT_DIRECTORY 1
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_WSL_DISTRIBUTIONS 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_WSL_DISTRIBUTION 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_WSL_PROCESSES 3
#define ZP_ADMINISTRATION_OPERATION_CONTROL_WSL_PROCESS 4
#define ZP_ADMINISTRATION_OPERATION_QUERY_UI_AUTOMATION_CHILDREN 1
#define ZP_ADMINISTRATION_OPERATION_QUERY_UI_AUTOMATION_PROPERTIES 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_PROXY_VPN 1
#define ZP_ADMINISTRATION_OPERATION_CONTROL_PROXY_VPN 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_CLIENT_STATUS 1
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_SYSTEM_PROTECTION 1
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_RESTORE_POINTS 2
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_SHADOW_COPIES 3
#define ZP_ADMINISTRATION_OPERATION_CONTROL_SYSTEM_PROTECTION 4
#define ZP_ADMINISTRATION_OPERATION_CONTROL_RESTORE_POINT 5
#define ZP_ADMINISTRATION_OPERATION_CONTROL_SHADOW_COPY 6
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_BITLOCKER_VOLUMES 1
#define ZP_ADMINISTRATION_OPERATION_ENUMERATE_BITLOCKER_PROTECTORS 2
#define ZP_ADMINISTRATION_OPERATION_CONTROL_BITLOCKER_VOLUME 3
#define ZP_ADMINISTRATION_OPERATION_CONTROL_BITLOCKER_PROTECTOR 4

typedef BYTE ZP_ADMINISTRATION_KIND, *PZP_ADMINISTRATION_KIND;

#define ZpAdministrationKindUser ((ZP_ADMINISTRATION_KIND)1)
#define ZpAdministrationKindDesktopProgram ((ZP_ADMINISTRATION_KIND)2)
#define ZpAdministrationKindWindowsApp ((ZP_ADMINISTRATION_KIND)3)
#define ZpAdministrationKindWindowsFeature ((ZP_ADMINISTRATION_KIND)4)
#define ZpAdministrationKindDevice ((ZP_ADMINISTRATION_KIND)5)
#define ZpAdministrationKindUpdate ((ZP_ADMINISTRATION_KIND)6)
#define ZpAdministrationKindTask ((ZP_ADMINISTRATION_KIND)7)
#define ZpAdministrationKindUpdateHistory ((ZP_ADMINISTRATION_KIND)8)
#define ZpAdministrationKindTaskFolder ((ZP_ADMINISTRATION_KIND)9)
#define ZpAdministrationKindFirewallProfile ((ZP_ADMINISTRATION_KIND)10)
#define ZpAdministrationKindFirewallRule ((ZP_ADMINISTRATION_KIND)11)
#define ZpAdministrationKindPowerSetting ((ZP_ADMINISTRATION_KIND)12)
#define ZpAdministrationKindPowerPlan ((ZP_ADMINISTRATION_KIND)13)
#define ZpAdministrationKindUps ((ZP_ADMINISTRATION_KIND)14)
#define ZpAdministrationKindSystemInformation ((ZP_ADMINISTRATION_KIND)15)
#define ZpAdministrationKindWlanInterface ((ZP_ADMINISTRATION_KIND)16)
#define ZpAdministrationKindWlanNetwork ((ZP_ADMINISTRATION_KIND)17)
#define ZpAdministrationKindWlanProfile ((ZP_ADMINISTRATION_KIND)18)
#define ZpAdministrationKindEnvironmentVariable ((ZP_ADMINISTRATION_KIND)19)
#define ZpAdministrationKindCertificateStore ((ZP_ADMINISTRATION_KIND)20)
#define ZpAdministrationKindCertificate ((ZP_ADMINISTRATION_KIND)21)
#define ZpAdministrationKindCertificateDetails ((ZP_ADMINISTRATION_KIND)22)
#define ZpAdministrationKindCertificateChain ((ZP_ADMINISTRATION_KIND)23)
#define ZpAdministrationKindClipboardFormat ((ZP_ADMINISTRATION_KIND)24)
#define ZpAdministrationKindClipboardState ((ZP_ADMINISTRATION_KIND)25)
#define ZpAdministrationKindWindowsCredential ((ZP_ADMINISTRATION_KIND)26)
#define ZpAdministrationKindWebCredential ((ZP_ADMINISTRATION_KIND)27)
#define ZpAdministrationKindFirmwareVariable ((ZP_ADMINISTRATION_KIND)28)
#define ZpAdministrationKindFirmwareBootEntry ((ZP_ADMINISTRATION_KIND)29)
#define ZpAdministrationKindCpuidSnapshot ((ZP_ADMINISTRATION_KIND)30)
#define ZpAdministrationKindSmbiosTable ((ZP_ADMINISTRATION_KIND)31)
#define ZpAdministrationKindAcpiTable ((ZP_ADMINISTRATION_KIND)32)
#define ZpAdministrationKindPublishedShare ((ZP_ADMINISTRATION_KIND)33)
#define ZpAdministrationKindNetworkConnection ((ZP_ADMINISTRATION_KIND)34)
#define ZpAdministrationKindNetworkAdapter ((ZP_ADMINISTRATION_KIND)35)
#define ZpAdministrationKindNetworkAdapterAddress ((ZP_ADMINISTRATION_KIND)36)
#define ZpAdministrationKindNetworkRoute ((ZP_ADMINISTRATION_KIND)37)
#define ZpAdministrationKindTcpEndpoint ((ZP_ADMINISTRATION_KIND)38)
#define ZpAdministrationKindUdpEndpoint ((ZP_ADMINISTRATION_KIND)39)
#define ZpAdministrationKindSession ((ZP_ADMINISTRATION_KIND)40)
#define ZpAdministrationKindLogonSession ((ZP_ADMINISTRATION_KIND)41)
#define ZpAdministrationKindPageFile ((ZP_ADMINISTRATION_KIND)42)
#define ZpAdministrationKindBluetoothRadio ((ZP_ADMINISTRATION_KIND)43)
#define ZpAdministrationKindBluetoothDevice ((ZP_ADMINISTRATION_KIND)44)
#define ZpAdministrationKindKeyboardEvent ((ZP_ADMINISTRATION_KIND)45)
#define ZpAdministrationKindLocation ((ZP_ADMINISTRATION_KIND)46)
#define ZpAdministrationKindFont ((ZP_ADMINISTRATION_KIND)47)

#define ZpAdministrationKindAppContainerProfile ((ZP_ADMINISTRATION_KIND)48)
#define ZpAdministrationKindAppContainerCapability ((ZP_ADMINISTRATION_KIND)49)
#define ZpAdministrationKindAppContainerBinary ((ZP_ADMINISTRATION_KIND)50)
#define ZpAdministrationKindObjectDirectory ((ZP_ADMINISTRATION_KIND)51)
#define ZpAdministrationKindObject ((ZP_ADMINISTRATION_KIND)52)
#define ZpAdministrationKindBattery ((ZP_ADMINISTRATION_KIND)53)
#define ZpAdministrationKindWslDistribution ((ZP_ADMINISTRATION_KIND)54)
#define ZpAdministrationKindWslProcess ((ZP_ADMINISTRATION_KIND)55)
#define ZpAdministrationKindUiAutomationElement ((ZP_ADMINISTRATION_KIND)56)
#define ZpAdministrationKindProxy ((ZP_ADMINISTRATION_KIND)57)
#define ZpAdministrationKindVpn ((ZP_ADMINISTRATION_KIND)58)
#define ZpAdministrationKindPackage ((ZP_ADMINISTRATION_KIND)59)
#define ZpAdministrationKindSoftwareDeployment ((ZP_ADMINISTRATION_KIND)60)
#define ZpAdministrationKindInputMethodContext ((ZP_ADMINISTRATION_KIND)61)
#define ZpAdministrationKindInputMethod ((ZP_ADMINISTRATION_KIND)62)
#define ZpAdministrationKindPackageContext ((ZP_ADMINISTRATION_KIND)63)
#define ZpAdministrationKindPackageProvider ((ZP_ADMINISTRATION_KIND)64)
#define ZpAdministrationKindClientStatus ((ZP_ADMINISTRATION_KIND)65)
#define ZpAdministrationKindClientEnvironmentVariable ((ZP_ADMINISTRATION_KIND)66)
#define ZpAdministrationKindUiAutomationProperty ((ZP_ADMINISTRATION_KIND)67)
#define ZpAdministrationKindSecurityDescriptor ((ZP_ADMINISTRATION_KIND)68)
#define ZpAdministrationKindUserProfile ((ZP_ADMINISTRATION_KIND)69)
#define ZpAdministrationKindSystemProtectionVolume ((ZP_ADMINISTRATION_KIND)70)
#define ZpAdministrationKindRestorePoint ((ZP_ADMINISTRATION_KIND)71)
#define ZpAdministrationKindShadowCopy ((ZP_ADMINISTRATION_KIND)72)
#define ZpAdministrationKindBitLockerVolume ((ZP_ADMINISTRATION_KIND)73)
#define ZpAdministrationKindBitLockerProtector ((ZP_ADMINISTRATION_KIND)74)
#define ZpAdministrationKindClipboardFile ((ZP_ADMINISTRATION_KIND)75)
// Package uses State for its provider engine. PackageProvider uses State for the engine and Flags for capabilities.
// PackageContext uses Name for the current account user name.
// InputMethodContext uses State for the session ID and Name for the current user name.
// InputMethod uses Identity for the layout/TIP ID, Description for language, and Detail for locale name.
#define ZP_ADMINISTRATION_WSL_FLAG_DEFAULT 0x80000000
#define ZP_ADMINISTRATION_APP_CONTAINER_FLAG_LOOPBACK 0x00000001
#define ZP_ADMINISTRATION_APP_CONTAINER_FLAG_PACKAGED 0x00000002
#define ZP_ADMINISTRATION_INPUT_METHOD_CONTEXT_FLAG_INTERACTIVE 0x00000001
#define ZP_ADMINISTRATION_INPUT_METHOD_FLAG_ENABLED 0x00000001
#define ZP_ADMINISTRATION_INPUT_METHOD_FLAG_ACTIVE 0x00000002
#define ZP_ADMINISTRATION_INPUT_METHOD_FLAG_DEFAULT 0x00000004
#define ZP_ADMINISTRATION_INPUT_METHOD_FLAG_INPUT_PROCESSOR 0x00000008
#define ZP_ADMINISTRATION_SECURITY_DESCRIPTOR_FLAG_DACL_PROTECTED 0x00000001
#define ZP_ADMINISTRATION_USER_PROFILE_FLAG_LOADED 0x00000001
#define ZP_ADMINISTRATION_USER_PROFILE_FLAG_SPECIAL 0x00000002
#define ZP_ADMINISTRATION_USER_PROFILE_FLAG_ROAMING_CONFIGURED 0x00000004
#define ZP_ADMINISTRATION_SYSTEM_PROTECTION_FLAG_SYSTEM_VOLUME 0x00000001
#define ZP_ADMINISTRATION_SHADOW_COPY_FLAG_CLIENT_ACCESSIBLE 0x00000001
#define ZP_ADMINISTRATION_SHADOW_COPY_FLAG_PERSISTENT 0x00000002
#define ZP_ADMINISTRATION_SHADOW_COPY_FLAG_NO_AUTO_RELEASE 0x00000004
#define ZP_ADMINISTRATION_SHADOW_COPY_FLAG_NO_WRITERS 0x00000008
#define ZP_ADMINISTRATION_SHADOW_COPY_FLAG_EXPOSED 0x00000010
#define ZP_ADMINISTRATION_SHADOW_COPY_FLAG_HARDWARE_ASSISTED 0x00000020
#define ZP_ADMINISTRATION_BITLOCKER_VOLUME_TYPE_MASK 0x00000003
#define ZP_ADMINISTRATION_BITLOCKER_PROTECTION_SHIFT 2
#define ZP_ADMINISTRATION_BITLOCKER_PROTECTION_MASK 0x0000000C
#define ZP_ADMINISTRATION_BITLOCKER_LOCK_SHIFT 4
#define ZP_ADMINISTRATION_BITLOCKER_LOCK_MASK 0x00000030
#define ZP_ADMINISTRATION_BITLOCKER_ENCRYPTION_METHOD_SHIFT 8
#define ZP_ADMINISTRATION_BITLOCKER_ENCRYPTION_METHOD_MASK 0x00000F00
#define ZP_ADMINISTRATION_BITLOCKER_FLAG_INITIALIZED 0x00001000
#define ZP_ADMINISTRATION_BITLOCKER_FLAG_AUTO_UNLOCK 0x00002000
#define ZP_ADMINISTRATION_BITLOCKER_FLAG_DATA_ONLY 0x00004000

#define ZP_ADMINISTRATION_FLAG_PARTIAL 0x80000000

#define ZP_ADMINISTRATION_CREDENTIAL_FLAG_SECRET_AVAILABLE 0x00000001
#define ZP_ADMINISTRATION_CREDENTIAL_FLAG_PROMPT 0x00000002
#define ZP_ADMINISTRATION_CREDENTIAL_PERSIST_SHIFT 8
#define ZP_ADMINISTRATION_CREDENTIAL_PERSIST_MASK 0x00000300

#define ZP_CERTIFICATE_INSTALL_FLAG_SOURCE_PATH 0x00000001
#define ZP_CERTIFICATE_INSTALL_FLAG_EXPORTABLE 0x00000002
// Install data is a little-endian password character count, UTF-16LE password, then a UTF-16LE path or file bytes.

typedef BYTE ZP_ADMINISTRATION_ACTION, *PZP_ADMINISTRATION_ACTION;

#define ZpAdministrationActionCreate ((ZP_ADMINISTRATION_ACTION)1)
#define ZpAdministrationActionDelete ((ZP_ADMINISTRATION_ACTION)2)
#define ZpAdministrationActionEnable ((ZP_ADMINISTRATION_ACTION)3)
#define ZpAdministrationActionDisable ((ZP_ADMINISTRATION_ACTION)4)
#define ZpAdministrationActionSetPassword ((ZP_ADMINISTRATION_ACTION)5)
#define ZpAdministrationActionRun ((ZP_ADMINISTRATION_ACTION)6)
#define ZpAdministrationActionStop ((ZP_ADMINISTRATION_ACTION)7)
#define ZpAdministrationActionInstall ((ZP_ADMINISTRATION_ACTION)8)
#define ZpAdministrationActionUninstall ((ZP_ADMINISTRATION_ACTION)9)
#define ZpAdministrationActionRefresh ((ZP_ADMINISTRATION_ACTION)10)
#define ZpAdministrationActionRename ((ZP_ADMINISTRATION_ACTION)11)
#define ZpAdministrationActionRestart ((ZP_ADMINISTRATION_ACTION)12)
#define ZpAdministrationActionCheck ((ZP_ADMINISTRATION_ACTION)13)
#define ZpAdministrationActionAllow ((ZP_ADMINISTRATION_ACTION)14)
#define ZpAdministrationActionBlock ((ZP_ADMINISTRATION_ACTION)15)
#define ZpAdministrationActionSleep ((ZP_ADMINISTRATION_ACTION)16)
#define ZpAdministrationActionHibernate ((ZP_ADMINISTRATION_ACTION)17)
#define ZpAdministrationActionShutdown ((ZP_ADMINISTRATION_ACTION)18)
#define ZpAdministrationActionSignOut ((ZP_ADMINISTRATION_ACTION)19)
#define ZpAdministrationActionLock ((ZP_ADMINISTRATION_ACTION)20)
#define ZpAdministrationActionActivate ((ZP_ADMINISTRATION_ACTION)21)
#define ZpAdministrationActionFirmware ((ZP_ADMINISTRATION_ACTION)22)
#define ZpAdministrationActionConfigure ((ZP_ADMINISTRATION_ACTION)23)
#define ZpAdministrationActionConnect ((ZP_ADMINISTRATION_ACTION)24)
#define ZpAdministrationActionDisconnect ((ZP_ADMINISTRATION_ACTION)25)
#define ZpAdministrationActionSetPermissions ((ZP_ADMINISTRATION_ACTION)26)
#define ZpAdministrationActionTurnOffDisplay ((ZP_ADMINISTRATION_ACTION)27)
#define ZpAdministrationActionUpgrade ((ZP_ADMINISTRATION_ACTION)28)
#define ZpAdministrationActionSetDefault ((ZP_ADMINISTRATION_ACTION)29)
#define ZpAdministrationActionEncrypt ((ZP_ADMINISTRATION_ACTION)30)
#define ZpAdministrationActionDecrypt ((ZP_ADMINISTRATION_ACTION)31)
#define ZpAdministrationActionPause ((ZP_ADMINISTRATION_ACTION)32)
#define ZpAdministrationActionResume ((ZP_ADMINISTRATION_ACTION)33)
#define ZpAdministrationActionUnlock ((ZP_ADMINISTRATION_ACTION)34)

#define ZP_SOFTWARE_ENGINE_MASK 0x0000000F
#define ZP_SOFTWARE_ENGINE_MSI 0x00000001
#define ZP_SOFTWARE_ENGINE_APPX 0x00000002
#define ZP_SOFTWARE_ENGINE_APP_INSTALLER 0x00000003
#define ZP_SOFTWARE_ENGINE_WINGET 0x00000004
#define ZP_SOFTWARE_ENGINE_PIP 0x00000005
#define ZP_SOFTWARE_ENGINE_NPM 0x00000006
#define ZP_SOFTWARE_ENGINE_CHOCOLATEY 0x00000007
#define ZP_SOFTWARE_ENGINE_DOTNET_TOOL 0x00000008
#define ZP_SOFTWARE_SOURCE_MASK 0x00000030
#define ZP_SOFTWARE_SOURCE_WINGET 0x00000010
#define ZP_SOFTWARE_SOURCE_STORE 0x00000020
#define ZP_SOFTWARE_SCOPE_MASK 0x00000300
#define ZP_SOFTWARE_SCOPE_USER 0x00000100
#define ZP_SOFTWARE_SCOPE_MACHINE 0x00000200
#define ZP_SOFTWARE_FLAG_ALL 0x00001000
#define ZP_SOFTWARE_PACKAGE_CAPABILITY_INSTALL 0x00000001
#define ZP_SOFTWARE_PACKAGE_CAPABILITY_UPGRADE 0x00000002
#define ZP_SOFTWARE_PACKAGE_CAPABILITY_UPGRADE_ALL 0x00000004
#define ZP_SOFTWARE_PACKAGE_CAPABILITY_UNINSTALL 0x00000008
#define ZP_SOFTWARE_DEPLOYMENT_ACTION_SHIFT 16
#define ZP_SOFTWARE_DEPLOYMENT_ACTION_MASK 0x001F0000
#define ZP_SOFTWARE_DEPLOYMENT_FLAG_REBOOT_REQUIRED 0x80000000
#define ZP_SOFTWARE_DEPLOYMENT_STATE_MASK 0x000000FF
#define ZP_SOFTWARE_DEPLOYMENT_PROGRESS_SHIFT 8
#define ZP_SOFTWARE_DEPLOYMENT_PROGRESS_MASK 0x003FFF00

#define ZP_SOFTWARE_DEPLOYMENT_STATE_QUEUED 1
#define ZP_SOFTWARE_DEPLOYMENT_STATE_RESOLVING 2
#define ZP_SOFTWARE_DEPLOYMENT_STATE_DOWNLOADING 3
#define ZP_SOFTWARE_DEPLOYMENT_STATE_INSTALLING 4
#define ZP_SOFTWARE_DEPLOYMENT_STATE_COMPLETED 5
#define ZP_SOFTWARE_DEPLOYMENT_STATE_FAILED 6

typedef struct _ZP_ADMINISTRATION_RECORD
{
    ZP_ADMINISTRATION_KIND Kind;
    ULONG State;
    ULONG Flags;
    ULONGLONG Value;
    PCWCH Identity;
    ULONG IdentityLength;
    PCWCH Name;
    ULONG NameLength;
    PCWCH Description;
    ULONG DescriptionLength;
    PCWCH Detail;
    ULONG DetailLength;
    const VOID* Data;
    ULONG DataLength;
} ZP_ADMINISTRATION_RECORD, *PZP_ADMINISTRATION_RECORD;

typedef const ZP_ADMINISTRATION_RECORD* PCZP_ADMINISTRATION_RECORD;

typedef struct _ZP_ADMINISTRATION_RECORD_VIEW
{
    ZP_ADMINISTRATION_KIND Kind;
    ULONG State;
    ULONG Flags;
    ULONGLONG Value;
    ZP_STRING_VIEW Identity;
    ZP_STRING_VIEW Name;
    ZP_STRING_VIEW Description;
    ZP_STRING_VIEW Detail;
    ZP_BUFFER_VIEW Data;
} ZP_ADMINISTRATION_RECORD_VIEW, *PZP_ADMINISTRATION_RECORD_VIEW;

typedef struct _ZP_ADMINISTRATION_LIST_VIEW
{
    const BYTE* Buffer;
    ULONG Length;
    ULONG Count;
} ZP_ADMINISTRATION_LIST_VIEW, *PZP_ADMINISTRATION_LIST_VIEW;

typedef const ZP_ADMINISTRATION_LIST_VIEW* PCZP_ADMINISTRATION_LIST_VIEW;

typedef struct _ZP_ADMINISTRATION_CONTROL_VIEW
{
    ZP_ADMINISTRATION_ACTION Action;
    ZP_STRING_VIEW Identity;
    ZP_STRING_VIEW Argument;
    ZP_STRING_VIEW Secret;
} ZP_ADMINISTRATION_CONTROL_VIEW, *PZP_ADMINISTRATION_CONTROL_VIEW;

typedef const ZP_ADMINISTRATION_CONTROL_VIEW* PCZP_ADMINISTRATION_CONTROL_VIEW;

typedef struct _ZP_ADMINISTRATION_DATA_CONTROL_VIEW
{
    ZP_ADMINISTRATION_ACTION Action;
    ULONG Flags;
    ZP_STRING_VIEW Identity;
    ZP_BUFFER_VIEW Data;
} ZP_ADMINISTRATION_DATA_CONTROL_VIEW, *PZP_ADMINISTRATION_DATA_CONTROL_VIEW;

typedef const ZP_ADMINISTRATION_DATA_CONTROL_VIEW* PCZP_ADMINISTRATION_DATA_CONTROL_VIEW;

NTSTATUS
ZpAdministration_EncodeRecord(
    _In_ PCZP_ADMINISTRATION_RECORD Record,
    _Out_writes_bytes_opt_(BufferSize) PVOID Buffer,
    _In_ ULONG BufferSize,
    _Out_ PULONG BytesWritten);

NTSTATUS
ZpAdministration_EncodeList(
    _In_reads_opt_(RecordCount) PCZP_ADMINISTRATION_RECORD Records,
    _In_ ULONG RecordCount,
    _Out_writes_bytes_opt_(BufferSize) PVOID Buffer,
    _In_ ULONG BufferSize,
    _Out_ PULONG BytesWritten);

NTSTATUS
ZpAdministration_DecodeList(
    _In_reads_bytes_(PayloadLength) const VOID* Payload,
    _In_ ULONG PayloadLength,
    _Out_ PZP_ADMINISTRATION_LIST_VIEW View);

NTSTATUS
ZpAdministration_GetNextRecord(
    _In_ PCZP_ADMINISTRATION_LIST_VIEW List,
    _Inout_ PULONG Offset,
    _Out_ PZP_ADMINISTRATION_RECORD_VIEW Record);

NTSTATUS
ZpAdministration_EncodeControl(
    _In_ ZP_ADMINISTRATION_ACTION Action,
    _In_reads_opt_(IdentityLength) PCWCH Identity,
    _In_ ULONG IdentityLength,
    _In_reads_opt_(ArgumentLength) PCWCH Argument,
    _In_ ULONG ArgumentLength,
    _In_reads_opt_(SecretLength) PCWCH Secret,
    _In_ ULONG SecretLength,
    _Out_writes_bytes_opt_(BufferSize) PVOID Buffer,
    _In_ ULONG BufferSize,
    _Out_ PULONG BytesWritten);

NTSTATUS
ZpAdministration_DecodeControl(
    _In_reads_bytes_(PayloadLength) const VOID* Payload,
    _In_ ULONG PayloadLength,
    _Out_ PZP_ADMINISTRATION_CONTROL_VIEW Control);

NTSTATUS
ZpAdministration_EncodeDataControl(
    _In_ ZP_ADMINISTRATION_ACTION Action,
    _In_ ULONG Flags,
    _In_reads_(IdentityLength) PCWCH Identity,
    _In_ ULONG IdentityLength,
    _In_reads_bytes_opt_(DataLength) const VOID* Data,
    _In_ ULONG DataLength,
    _Out_writes_bytes_opt_(BufferSize) PVOID Buffer,
    _In_ ULONG BufferSize,
    _Out_ PULONG BytesWritten);

NTSTATUS
ZpAdministration_DecodeDataControl(
    _In_reads_bytes_(PayloadLength) const VOID* Payload,
    _In_ ULONG PayloadLength,
    _Out_ PZP_ADMINISTRATION_DATA_CONTROL_VIEW Control);

NTSTATUS
ZpAdministration_EncodeQuery(
    _In_reads_(IdentityLength) PCWCH Identity,
    _In_ ULONG IdentityLength,
    _Out_writes_bytes_opt_(BufferSize) PVOID Buffer,
    _In_ ULONG BufferSize,
    _Out_ PULONG BytesWritten);

NTSTATUS
ZpAdministration_DecodeQuery(
    _In_reads_bytes_(PayloadLength) const VOID* Payload,
    _In_ ULONG PayloadLength,
    _Out_ PZP_STRING_VIEW Identity);

EXTERN_C_END
