<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="RunCodeAnalysis">
  <PropertyGroup>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>$(Platform)</PlatformTarget>
    <OutputPath>..\OutDir\$(Platform)\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KNSoft.ZPigeon.Agent\KNSoft.ZPigeon.Agent.csproj" />
    <ProjectReference Include="..\KNSoft.ZPigeon.Tools\KNSoft.ZPigeon.Tools.csproj" />
  </ItemGroup>
</Project>
