#pragma once

#include <KNSoft/NDK/NDK.h>

typedef
NTSTATUS
(NTAPI *ZP_TRANSPORT_START_ROUTINE)(
    _In_opt_ PVOID Context);

typedef
VOID
(NTAPI *ZP_TRANSPORT_STOP_ROUTINE)(
    _In_opt_ PVOID Context);

typedef struct _ZP_TRANSPORT_OPERATIONS
{
    ZP_TRANSPORT_START_ROUTINE Start;
    ZP_TRANSPORT_STOP_ROUTINE Stop;
} ZP_TRANSPORT_OPERATIONS, *PZP_TRANSPORT_OPERATIONS;

typedef const ZP_TRANSPORT_OPERATIONS* PCZP_TRANSPORT_OPERATIONS;
